services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    container_name: keycloak
    network_mode: host
    restart: unless-stopped
    command: ["start-dev", "--db=dev-file"]
    environment:
      # Admin user (Keycloak creates this on first start)
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin_change_me

      # Hostname settings (dev-friendly)
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: "http://localhost:8080"
      # optional but fine
      KC_HOSTNAME_ADMIN: "http://localhost:8080"
      KC_HOSTNAME_BACKCHANNEL_DYNAMIC: "true"

      # KC_HOSTNAME: localhost

      # Optional: set proxy mode if you put it behind nginx/traefik later
      # KC_PROXY: edge
    volumes:
      - keycloak_data:/opt/keycloak/data

volumes:
  keycloak_data:
